name: common
description: "A new Flutter package project."
version: 0.0.1
publish_to: none
homepage:

environment:
  sdk: '>=3.4.3 <4.0.0'
  flutter: ">=1.17.0"


dependencies:
  flutter:
    sdk: flutter
  account: 
    path: ../account
  flutter_riverpod: ^2.5.1
  go_router: ^14.2.1
  # https://pub.dev/packages/retrofit
  retrofit: ^4.2.0
  dio: ^5.5.0+1  
  # https://pub.dev/packages/upgrader
  upgrader: ^10.3.0
  # https://pub.dev/packages/logger
  logger: ^2.4.0
  # https://pub.dev/packages/dio_http_formatter
  dio_http_formatter: ^3.2.1
  # https://pub.dev/packages/freezed_annotation
  freezed_annotation: ^2.4.4
  # https://pub.dev/packages/json_annotation
  json_annotation: ^4.9.0
  # https://pub.dev/packages/firebase_core
  firebase_core: ^3.2.0
  # https://pub.dev/packages/firebase_auth
  firebase_auth: ^5.1.2 
  # https://pub.dev/packages/firebase_crashlytics
  firebase_crashlytics: ^4.0.3
  # https://pub.dev/packages/firebase_analytics
  firebase_analytics: ^11.2.0
  # https://pub.dev/packages/firebase_messaging
  firebase_messaging: ^15.0.3
  # https://pub.dev/packages/firebase_performance
  firebase_performance: ^0.10.0
  # https://pub.dev/packages/firebase_remote_config
  firebase_remote_config: ^5.0.3
  # https://pub.dev/packages/flutter_local_notifications
  flutter_local_notifications: ^17.2.1
  # https://pub.dev/packages/pinput
  pinput: ^5.0.0
  # https://pub.dev/packages/multiple_result
  multiple_result: ^5.1.0
  # https://pub.dev/packages/flutter_secure_storage
  flutter_secure_storage: ^9.2.2
  # https://pub.dev/packages/intl
  intl: ^0.19.0  
  # https://pub.dev/packages/connectivity_plus
  connectivity_plus: ^6.0.5
  # https://pub.dev/packages/internet_connection_checker
  internet_connection_checker: ^2.0.0
  # https://pub.dev/packages/envied
  envied: ^0.5.4+1
  # https://pub.dev/packages/cached_network_image/
  cached_network_image: ^3.3.1
  # https://pub.dev/packages/flutter_cache_manager/
  flutter_cache_manager: ^3.3.2
  #https://pub.dev/packages/loading_animation_widget
  loading_animation_widget: ^1.2.1
  #https://pub.dev/packages/google_fonts/
  google_fonts: ^6.2.1
  # https://pub.dev/packages/flutter_styled_toast
  flutter_styled_toast: ^2.2.1
  # https://pub.dev/packages/mask_text_input_formatter/
  mask_text_input_formatter: ^2.9.0
  # https://pub.dev/packages/image_picker
  image_picker: ^1.1.2
  # https://pub.dev/packages/flutter_svg
  flutter_svg: ^2.0.10+1
  # https://pub.dev/packages/loader_overlay
  loader_overlay: ^4.0.0
  # https://pub.dev/packages/timezone/install
  timezone: ^0.9.4
  # https://pub.dev/packages/isar
  isar: 
    version: 3.1.8
    hosted: https://pub.isar-community.dev/
  isar_flutter_libs: # contains Isar Core
    version: 3.1.8
    hosted: https://pub.isar-community.dev/
  # https://pub.dev/packages/hugeicons
  hugeicons: ^0.0.7
  # https://pub.dev/packages/mime
  mime: ^1.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  build_runner: ^2.4.11
  envied_generator: ^0.5.4+1
  retrofit_generator: '>=8.1.2'
  json_serializable: '^6.8.0'
  freezed: ^2.5.7
  riverpod_generator: ^2.4.2
  riverpod_lint: ^2.3.12
  custom_lint: ^0.6.4
  flutter_gen_runner: ^5.4.0
  flutter_translation_sheet: ^1.0.33-dev.1

dependency_overrides: 
  meta: 1.15.0

flutter_gen:
  output: lib/gen/ # Optional (default: lib/gen/)
  line_length: 80 # Optional (default: 80)

  assets:
    outputs:
      package_parameter_enabled: true

  # Optional
  integrations:
    flutter_svg: true
    flare_flutter: true
    rive: true
    lottie: true

flutter:
  uses-material-design: true

  assets:
    - assets/i18n/
    - google_fonts/
    - assets/images/
    - assets/images/logo/
    - assets/images/social/
    - assets/icons/
