targets:
  $default:
    builders:
      envied_generator:
        generate_for:
          include:
            - lib/core/env**/*.dart

      # riverpod_generator:
      #   generate_for:
      #     include:
      #       - "**/providers/**.dart"
      #       - "**/**_provider.dart"

      # go_router_builder:
      #   generate_for:
      #     include:
      #       - "lib/core/routes.dart"
      #     exclude:
      #      - "lib/features/**.dart"