name: core
description: A new Flutter package project.
version: 0.0.1
publish_to: none
homepage:

environment:
  sdk: '>=3.4.3 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  common:
    path: ../common
  analytic:
    path: ../analytic



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  build_runner: any
  envied_generator: ^0.5.4+1
  retrofit_generator: '>=8.1.2'
  json_serializable: '^6.8.0'
  freezed: ^2.5.7
  riverpod_generator: ^2.4.2
  riverpod_lint: ^2.3.12
  custom_lint: ^0.6.4
  flutter_gen_runner: ^5.4.0
  flutter_translation_sheet: ^1.0.33-dev.1
  isar_generator: 
    version: 3.1.8
    hosted: https://pub.isar-community.dev/

#https://dart.dev/tools/pub/dependencies
dependency_overrides:
  meta: 1.15.0


# The following section is specific to Flutter packages.
flutter:
  uses-material-design: true

  # To add assets to your package, add an assets section, like this:
  # assets:
    #- .dev.env
    #- .qa.env  
    #- .prod.env

